### ISSUE TITLE
install schema fails with syntax error

### ISSUE THREAD

**Issue by dongourley** [IUMDPI/MediaSCORE#1]
I am trying to install MediaSCORE on Ubuntu 14.04 with Mysql 5.5.46. When I get to the step in install.txt to connect to the database and <code>source data/sql/schema.sql</code> it fails with this message:

```
ERROR 1064 (42000) at line 11: You have an error in your SQL syntax;
check the manual that  corresponds to your MySQL server version for the
right syntax to use near '<<<<<<< HEAD
=======
CREATE TABLE `characteristics_format` (
  `id` bigint(20) N' at line 1
```

It seems to be the <<<<<<<< and >>>>>>>>> lines it doesn't like -- I'm not sure what they are and where they come from...are they an artifact from git or symfony or ...? Also there are two CREATE stmts for characteristics_format and other tables with the <<<<<<< HEAD and >>>>>>> blocks, so I'm guessing that something is supposed to process schema.sql before I feed it to MySQL?

The previous install.txt step, <code>php symfony --model --forms --filters</code> did not work -- it just listed all the available tasks. So I ran these three commands instead:

```
php symfony doctrine:build-model
php symfony doctrine:build-forms
php symfony doctrine:build-filters
```

Did that miss something that processes the schema file?

**Comment by Fuqran** [comment]
looks like you have conflict in your schema.sql file.Please resolve the
conflict and try using schema.yml
php symfony propel:build-sql
http://symfony.com/legacy/doc/cookbook/1_2/en/cli

On Fri, Jan 22, 2016 at 6:30 PM, Don notifications@github.com wrote:

> I am trying to install MediaSCORE on Ubuntu 14.04 with Mysql 5.5.46. When
> I get to the step in install.txt to connect to the database and source
> data/sql/schema.sql it fails with this message:
> 
> ERROR 1064 (42000) at line 11: You have an error in your SQL syntax;
> check the manual that  corresponds to your MySQL server version for the
> 
> # right syntax to use near '<<<<<<< HEAD
> 
> CREATE TABLE `characteristics_format` (
>   `id` bigint(20) N' at line 1
> 
> It seems to be the <<<<<<<< and >>>>>>>>> lines it doesn't like -- I'm not
> sure what they are and where they come from...are they an artifact from git
> or symfony or ...? Also there are two CREATE stmts for
> characteristics_format and other tables with the <<<<<<< HEAD and >>>>>>>
> blocks, so I'm guessing that something is supposed to process schema.sql
> before I feed it to MySQL?
> 
> The previous install.txt step, php symfony --model --forms --filters did
> not work -- it just listed all the available tasks. So I ran these three
> commands instead:
> 
> php symfony doctrine:build-model
> php symfony doctrine:build-forms
> php symfony doctrine:build-filters
> 
> Did that miss something that processes the schema file?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IUMDPI/MediaSCORE/issues/1.

## 

Thanks!
Furqan Wasi
Application Developer

office: 888-783-2442

[image: https://twitter.com/geekschicago] https://twitter.com/geekschicago
 [image: https://www.facebook.com/geekschicago]
https://www.facebook.com/geekschicago [image:
https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA]
https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA [image:
https://www.linkedin.com/company/geekschicago-com]
https://www.linkedin.com/company/geekschicago-com
https://geekschicago.com

**Comment by dongourley** [comment]
Thanks. It seems this application is using doctrine ORM, not Propel:

```
/var/www/MediaSCORE> php symfony propel:build-sql                                                   
There are no tasks defined in the "propel" namespace.  
```

When I re-generate the SQL with <code>php symfony doctrine:build-sql</code> I get some other syntax errors, like:

```
ERROR 1064 (42000): You have an error in your SQL syntax;
check the manual that corresponds to your MySQL server version for the right syntax to use near
'datatime, score_subject_interest FLOAT(18, 2), notes_subject_interest text, scor' at line 1
```

Full output is attached:
[source.err.txt](https://github.com/IUMDPI/MediaSCORE/files/100886/source.err.txt)

Thanks for your help...

**Comment by Fuqran** [comment]
welcome, yes it is using doctrine , let me know if you need more help ​

On Fri, Jan 22, 2016 at 7:23 PM, Don notifications@github.com wrote:

> Thanks. It seems this application is using doctrine ORM, not Propel:
> 
> /var/www/MediaSCORE> php symfony propel:build-sql
> There are no tasks defined in the "propel" namespace.
> 
> When I re-generate the SQL with php symfony doctrine:build-sql I get some
> other syntax errors, like:
> 
> ERROR 1064 (42000): You have an error in your SQL syntax;
> check the manual that corresponds to your MySQL server version for the right syntax to use near
> 'datatime, score_subject_interest FLOAT(18, 2), notes_subject_interest text, scor' at line 1
> 
> Full output is attached:
> source.err.txt
> https://github.com/IUMDPI/MediaSCORE/files/100886/source.err.txt
> 
> Thanks for your help...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IUMDPI/MediaSCORE/issues/1#issuecomment-173933176.

## 

Thanks!
Furqan Wasi
Application Developer

office: 888-783-2442

[image: https://twitter.com/geekschicago] https://twitter.com/geekschicago
 [image: https://www.facebook.com/geekschicago]
https://www.facebook.com/geekschicago [image:
https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA]
https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA [image:
https://www.linkedin.com/company/geekschicago-com]
https://www.linkedin.com/company/geekschicago-com
https://geekschicago.com

**Comment by dongourley** [comment]
Thanks -- I need help generating or editing a schema.sql file that I can successfully use to build the mediascore database.

**Comment by Fuqran** [comment]
Please follow this link

schema.yml also exists in the project
this command will help you out in creating the the sql scheme and update
the database

php symfony doctrine:build-schema

follow the link below for more help
http://symfony.com/legacy/doc/jobeet/1_4/en/03?orm=Doctrine

On Fri, Jan 22, 2016 at 7:30 PM, Don notifications@github.com wrote:

> Thanks -- I need help generating or editing a schema.sql file that I can
> successfully use to build the mediascore database.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IUMDPI/MediaSCORE/issues/1#issuecomment-173935383.

## 

Thanks!
Furqan Wasi
Application Developer

office: 888-783-2442

[image: https://twitter.com/geekschicago] https://twitter.com/geekschicago
 [image: https://www.facebook.com/geekschicago]
https://www.facebook.com/geekschicago [image:
https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA]
https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA [image:
https://www.linkedin.com/company/geekschicago-com]
https://www.linkedin.com/company/geekschicago-com
https://geekschicago.com

**Comment by bdwheele** [comment]
```
Hello!

There is a schema.sql that's in MediaSCORE/data/sql which should be
correct for creating the necessary database structure.  I updated it
3 months ago to fix some dependency issues, so it should be correct.

Brian


On 01/22/2016 09:53 AM, Furqan Wasi
  wrote:



  Please follow this link

  schema.yml also exists in the project
  this command will help you out in creating the the sql scheme and
  update
  the database

  php symfony doctrine:build-schema

  follow the link below for more help
  http://symfony.com/legacy/doc/jobeet/1_4/en/03?orm=Doctrine

  On Fri, Jan 22, 2016 at 7:30 PM, Don
  <notifications@github.com> wrote:

  > Thanks -- I need help generating or editing a schema.sql file
  that I can
  > successfully use to build the mediascore database.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/IUMDPI/MediaSCORE/issues/1#issuecomment-173935383.
      >

```
  -- 

  Thanks!
  Furqan Wasi
  Application Developer

  office: 888-783-2442

  [image: https://twitter.com/geekschicago]
  <https://twitter.com/geekschicago>
  [image: https://www.facebook.com/geekschicago]
  <https://www.facebook.com/geekschicago> [image:
  https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA]
  <https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA>
  [image:
  https://www.linkedin.com/company/geekschicago-com]
  <https://www.linkedin.com/company/geekschicago-com>
  <https://geekschicago.com>
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by dongourley** [comment]
Brian, thanks for your response. My problem is that data/sql/schema.sql has these <<<<<<HEAD lines that MySQL chokes on. What is that about?

**Comment by bdwheele** [comment]
```
When it pushed the changes, it apparently was pushing a diff of some
sort.

I've attached what should be the correct one, and I'll see if I can
get the git repo updated.

Brian


On 01/22/2016 11:32 AM, Don wrote:



  Brian, thanks for your response. My problem is that
  data/sql/schema.sql has these <<<<<<HEAD lines
  that MySQL chokes on. What is that about?

  > On Jan 22, 2016, at 11:03 AM, bdwheele
  <notifications@github.com> wrote:
  > 
  > 
  > 
  > 
  > 
  > 
  > Hello!
  > 
  > There is a schema.sql that's in MediaSCORE/data/sql which
  should be
  > correct for creating the necessary database structure. I
  updated it
  > 3 months ago to fix some dependency issues, so it should be
  correct.
  > 
  > Brian
  > 
  > 
  > On 01/22/2016 09:53 AM, Furqan Wasi
  > wrote:
  > 
  > 
  > 
  > Please follow this link
  > 
  > schema.yml also exists in the project
  > this command will help you out in creating the the sql scheme
  and
  > update
  > the database
  > 
  > php symfony doctrine:build-schema
  > 
  > follow the link below for more help
  > http://symfony.com/legacy/doc/jobeet/1_4/en/03?orm=Doctrine
  > 
  > On Fri, Jan 22, 2016 at 7:30 PM, Don
  > <notifications@github.com> wrote:
  > 
  > > Thanks -- I need help generating or editing a schema.sql
  file
  > that I can
  > > successfully use to build the mediascore database.
  > >
  > > —
  > > Reply to this email directly or view it on GitHub
  > >
  >
```

https://github.com/IUMDPI/MediaSCORE/issues/1#issuecomment-173935383.
      > >
      > 
      > 
      > 
      > -- 
      > 
      > Thanks!
      > Furqan Wasi
      > Application Developer
      > 
      > office: 888-783-2442
      > 
      > [image: https://twitter.com/geekschicago]
      > https://twitter.com/geekschicago
      > [image: https://www.facebook.com/geekschicago]
      > https://www.facebook.com/geekschicago [image:
      > https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA]
      >
      https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA
      > [image:
      > https://www.linkedin.com/company/geekschicago-com]
      > https://www.linkedin.com/company/geekschicago-com
      > https://geekschicago.com
      > —
      > Reply to this email directly or view
      > it on GitHub.
      > —
      > Reply to this email directly or view it on GitHub.
      > 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by dongourley** [comment]
Thanks again Brian. I am out right now but I'll give this schema file a try as soon as I can. 

Can you look at my initial issue description and verify the symfony build cmds I used? If correct I can submit a pull request for updated install.txt if that is helpful.

**Comment by bdwheele** [comment]
```
Hi Don

I'm really not in any position to support the software.  I'm the
sysadmin that our instance runs on, and I just tinkered with the
setup to get it to work here.

Brian

On 01/22/2016 12:09 PM, Don wrote:



  Thanks again Brian. I am out right now but I'll give this schema
  file a try as soon as I can. 

  Can you look at my initial issue description and verify the
  symfony build cmds I used? If correct I can submit a pull request
  for updated install.txt if that is helpful. 

  > On Jan 22, 2016, at 12:00 PM, bdwheele
  <notifications@github.com> wrote:
  > 
  > 
  > 
  > 
  > 
  > 
  > When it pushed the changes, it apparently was pushing a diff
  of some
  > sort.
  > 
  > I've attached what should be the correct one, and I'll see if
  I can
  > get the git repo updated.
  > 
  > Brian
  > 
  > 
  > On 01/22/2016 11:32 AM, Don wrote:
  > 
  > 
  > 
  > Brian, thanks for your response. My problem is that
  > data/sql/schema.sql has these <<<<<<HEAD
  lines
  > that MySQL chokes on. What is that about?
  > 
  > > On Jan 22, 2016, at 11:03 AM, bdwheele
  > <notifications@github.com> wrote:
  > > 
  > > 
  > > 
  > > 
  > > 
  > > 
  > > Hello!
  > > 
  > > There is a schema.sql that's in MediaSCORE/data/sql
  which
  > should be
  > > correct for creating the necessary database structure. I
  > updated it
  > > 3 months ago to fix some dependency issues, so it should
  be
  > correct.
  > > 
  > > Brian
  > > 
  > > 
  > > On 01/22/2016 09:53 AM, Furqan Wasi
  > > wrote:
  > > 
  > > 
  > > 
  > > Please follow this link
  > > 
  > > schema.yml also exists in the project
  > > this command will help you out in creating the the sql
  scheme
  > and
  > > update
  > > the database
  > > 
  > > php symfony doctrine:build-schema
  > > 
  > > follow the link below for more help
  > >
  http://symfony.com/legacy/doc/jobeet/1_4/en/03?orm=Doctrine
  > > 
  > > On Fri, Jan 22, 2016 at 7:30 PM, Don
  > > <notifications@github.com> wrote:
  > > 
  > > > Thanks -- I need help generating or editing a
  schema.sql
  > file
  > > that I can
  > > > successfully use to build the mediascore database.
  > > >
  > > > —
  > > > Reply to this email directly or view it on GitHub
  > > >
  > >
  >
```

https://github.com/IUMDPI/MediaSCORE/issues/1#issuecomment-173935383.
      > > >
      > > 
      > > 
      > > 
      > > -- 
      > > 
      > > Thanks!
      > > Furqan Wasi
      > > Application Developer
      > > 
      > > office: 888-783-2442
      > > 
      > > [image: https://twitter.com/geekschicago]
      > > https://twitter.com/geekschicago
      > > [image: https://www.facebook.com/geekschicago]
      > > https://www.facebook.com/geekschicago [image:
      > >
      https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA]
      > >
      >
      https://www.youtube.com/channel/UCS76Te3JZO4bClkrYD3QVrA
      > > [image:
      > > https://www.linkedin.com/company/geekschicago-com]
      > >
      https://www.linkedin.com/company/geekschicago-com
      > > https://geekschicago.com
      > > —
      > > Reply to this email directly or view
      > > it on GitHub.
      > > —
      > > Reply to this email directly or view it on GitHub.
      > > 
      > —
      > Reply to this email directly or view
      > it on GitHub.
      > —
      > Reply to this email directly or view it on GitHub.
      > 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by dongourley** [comment]
Brian - thanks for your help. The data/sql/schema.sql-20160122 that you put in the repository worked and I now have the application up on the web server.
